### ISSUE TITLE
wrong place on leaderboard

### ISSUE THREAD

**Issue by DanimalSounds** [Avasam/Global_speedrunning_leaderboard#7]
For a couple of games, I have the exact same time as other people on the leaderboard. for instance, Pokemon Snap, any% n64... http://www.speedrun.com/pkmnsnap

I am getting placed 12th on the leaderboard, but my time is tied for 11th. It is lowering my points.

**Comment by DanimalSounds** [comment]
sorry, I see that this is an issue that was closed before... but I noticed it was happening to me today.

**Comment by Avasam** [comment]
Similarly to #3 : The decision to untie rankings' score based on the date is due to games with lots of ties (especially near last place). As much as I like "meme runs", some games would become almost required to have a lot of points without giving any real efforts. (see [Barney's Hide and Seek Game - Any%](http://www.speedrun.com/Barneys_Hide_and_Seek_Game#Any))

This also keeps the prestige of being the first to get a certain time.

**Comment by Avasam** [comment]
I should mention this was made irrelevant by #10 Relative time based score.
No more worries about ties giving you way less points than the next guy.
